makefile, src/dll/edbgEcmdDll.C
This pulls in the latest ecmd and pdbg code updates.  This is to both stay up to date and pull in a pdbg fix for p1 on host systems.
=> Pull in latest subrepo updates

src/dll/edbgEcmdDll.C
1) Use mem instead of adu
2) Use mem_read instead of adu_getmem and adu_getmem_io -
Functions with adu prefix will be deprecated and removed in future.
=> get/put memproc to use mem_read instead adu_getmem/adu_getmem_io

config.py, makefile
Refined what is built in ecmd, resulting in ~25% faster build
Updated to latest ecmd15 to pull in new support that fixes our
build warning for define redefinition
Moved to latest pdbg to stay current
Signed-off-by: Jason Albert <albertj@us.ibm.com>
=> Updates to ecmd & pdbg repos, build speedup

bin/edbgBmcWrapper.sh
While the DTB location is still being finalized, trust PDBG_DTB to point to the right device tree.
If PDBG_DTB is set, then use that as the device tree.
=> Fix setting of EDBG_DTB

src/dll/edbgEcmdDll.C
Eexisting libipl.h is changed to libipl.H, libipl.h uses "C" compiler
and libipl.H uses C++ compiler.
Made changes to use new libipl.H header file.
=> Fix change in header file name from libipl

src/dll/edbgEcmdDll.C
Reverting back the changes as the libipl changes to rename the
header files are in review and is going to take time to get to merge.
Will push back the original patch after libipl changes are merged.
=> Revert back libipl header file rename

makefile
The creation of the file got lost in the previous speed up of
the ecmd part of the build
Signed-off-by: Jason Albert <albertj@us.ibm.com>
=> Added ecmd.htxt generation

src/dll/edbgEcmdDll.C
libipl.h has been renamed as libipl.H i.e from C to C++
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
=> Cater for change in ipl header file

meson.build
1) Updated to latest ecmd code to pickup all the updates including python3 updates in ecmd.
2) Move from python to python3 environment in makeext.py
3) Moving from python to python3 in meson build for ecmd-pdbg
=> ecmd submodule update and python3 enablement

bin/edbgBmcWrapper.sh, bin/updatemodel, bin/updateserial, makefile, src/dll/edbgEcmdDll.C, src/meson.build, src/p9/p9_edbgEcmdDllScom.C, src/p9/p9_edbgEcmdDllScom.H
1. pdbg submodule update to the latest upstream SHA
2. p9 scom refactor to support multiple platforms at runtime
3. Refactor initTargets() and other places referencing EDBG_DTB to move to PDBG_DTB
=> P9 scom refactor

bin/edbgdetcnfg, makefile, src/p10/p10_edbgEcmdDllScom.C
Newer version of bash don't like using cat to read the eeprom label value and generate warning messages.  The update removes those warnings and doesn't change function.
Also included are compile issue fixes encountered when trying to package this update.
=> Fix null byte messages

src/istep/edbgIstep.C, src/p10/p10_edbgEcmdDllScom.C
Fix the errors generated while using the latest libraries
Error information:
| ../git/src/istep/edbgIstep.C:584:27: error: aggregate 'std::array<char, 128> buffer' has incomplete type and cannot be defined
|   584 |     std::array<char, 128> buffer;
| ../git/src/p10/p10_edbgEcmdDllScom.C:223:23: error: declaration of 'path' shadows a previous local [-Werror=shadow]
|   223 |           const char *path = pdbg_target_path(target);
Signed-off-by: deepakala-k <deepakala.karthikeyan@ibm.com>
=> Resolve compilation error

README.md, meson.build
The git init and update command when part of meson fails while the recipe is built using bitbake. So removed the git init and update commands and let the recipe pull the ecmd repo as part of ecmd-pdbg
Signed-off-by: Deepa Karthikeyan <deepakala.karthikeyan@ibm.com>
=> Fix CI build failure

src/istep/p10/help/istep_list.htxt
Some of the istep name does not match the actual steps run. Fixing it helps in resolving the below issue as the users tend to use the listed name for further commands.
Using the wrong istep name listed throws error
host_fbc_eff_config_aggregate <-- wrong istep name proc_fbc_eff_config_aggregate <-- correct istep name
Requested iStep-End not recognized: host_fbc_eff_config_aggregate. Returning rc=0x100104f
ERROR: (ECMD): istep - Problems running iSteps ERROR: (ECMD): ecmd - 'istep' returned with error code 0x100104F (ERROR OPENING DECODE FILE) /usr/bin/edbg istep poweron..host_fbc_eff_config_aggregate
Signed-off-by: deepakala <deepakala.karthikeyan@ibm.com>
=> Fix istep name displayed on 'istep list'

meson.build, meson_options.txt, src/common/edbgOutput.C, src/dll/edbgEcmdDll.C, src/meson.build
use case:
When user executes ecmd-pdbg 'istep' command, ecmd-pdbg, ipl traces were not logged into the journal and it is difficult to trace any error.
register callbacks from ipl, pdbg, liekb library and redirect them to terminal and journal (if enabled)
Now with the compile time flag "-Djournal=enabled" the logs will be added to journal and terminal with the LOG_INFO priority. If the compile time flag is NOT provided, then the logs are printed only onto the terminal.
Signed-off-by: Deepa Karthikeyan <deepakala.karthikeyan@ibm.com>
=> Add support to log traces into journal

src/dll/edbgEcmdDll.C, src/p10/p10_edbgEcmdDllScom.C
getscom pu.perv 000F0040 -p0 -call
When the target is not enabled, the above getscom command used to list the targets that are not enabled and display junk values
That is addressed in this commit.
Test output:
bmc:~# getscom pu.perv 000F0040 -p0 -call
pu.perv k0:n0:s0:p00:c2    0x9C201C0000000000
pu.perv k0:n0:s0:p00:c3    0x9C201C0000000000
pu.perv k0:n0:s0:p00:c8    0x8020000100000000
pu.perv k0:n0:s0:p00:c9    0x8020000100000000
pu.perv k0:n0:s0:p00:c12   0xA020000100000000
pu.perv k0:n0:s0:p00:c13   0xA020000100000000
pu.perv k0:n0:s0:p00:c16   0x9C20000000000000
pu.perv k0:n0:s0:p00:c17   0x9C20000000000000
pu.perv k0:n0:s0:p00:c18   0x9C20000000000000
pu.perv k0:n0:s0:p00:c19   0x9C20000000000000
pu.perv k0:n0:s0:p00:c26   0xA020000100000000
pu.perv k0:n0:s0:p00:c27 …
=> ecmd-pdbg: Fix getscom to handle target not enabled

src/dll/edbgEcmdDll.C
When the targets are not functional and probed, it corrupts some other register. Due to this, getscom/ putsom were NOT working
Fix: Allow only functional targets.
Tested: Ran the regression tests and verified that the getscoms and putscoms work correctly.
=> ecmd-pdbg: Fix getscom to allow only functional targets

src/p10/ekb/p10_scom_addr.C
The latest ekb code does not look for the address's getSatOffset() to be less
than 16.
The getSatOffset information is the bit0 to bit31 of the address
provided. The omic addresses fall outside that range.
Fix:
Mirroed the isOmictarget() method from the ekb and it fixed the issue.
Test Results:
getscom pu.omic 0C011422 -all
pu.omic k0:n0:s0:p00:c1    0x0000FF5100040020
pu.omic k0:n0:s0:p02:c1    0x0000FF5100040020
/usr/bin/edbg getscom pu.omic 0C011422 -all
p10bmc:/tmp# pdbg -P omic getscom 0x0C011422
p0: 0x000000000c011422 = 0x0000000000000000 (/proc0/pib/perv12/mc0/omic0)
p0: 0x000000000c011822 = 0x0000ff5100040020 (/proc0/pib/perv12/mc0/omic1)
p2: 0x000000000c011422 = 0x0000000000000000 (/proc2/pib/perv12/mc0/omic0)
p2: 0x000000000c011822 = 0x0000ff5100040020 …
=> Fix omic getscom

src/p10/ekb/p10_scom_addr.C, src/p10/ekb/p10_scom_addr.H, src/p10/ekb/p10_scominfo.C, src/p10/ekb/p10_spr_name_map.C, src/p10/ekb/p10_spr_name_map.H, src/p10/ekb/p10_spr_name_map_info.H
The ecmd-pdbg consists of ekb files and as they are not mirrored, any recent updates to ekb repo is not part of ecmd-pdbg. So, Updating the ecmd-pdbg with the latest ekb files.
Signed-off-by: Parasa Swetha <Parasa.Swetha1@ibm.com>
Change-Id: I0f67a726eb358b963cc8d3956db124a125bc5f97
=> Mirroring ecmd-pdbg with latest ekb files

src/istep/edbgIstep.C, src/istep/p10/help/istep_list.htxt
The istep 16.3 performs "No-op" but is marked as "host_secure_rng" in istep list.so changing it to "No-op".
Before:
``` host_activate_boot_core                  16     Activate boot core
host_activate_secondary_cores            16     Activate secondary cores
host_secure_rng                          16     Secure the random number  --> Marked Incorrectly
mss_scrub                                16     Start background scrub
host_ipl_complete                        16     Notify SP drawer ipl complete
```
After:
```host_activate_boot_core                  16     Activate boot core
host_activate_secondary_cores            16     Activate secondary cores
No-op                                    16                               --> changed to No-op
mss_scrub                                16 …
```
=> Fix istep(16.3) that was named incorrectly

src/common/edbgCommon.C, src/common/edbgCommon.H, src/dll/edbgEcmdDll.C, src/p10/p10_edbgEcmdDllScom.C, src/p10/p10_edbgEcmdDllScom.H
Added the changes to support odyssey chip and chipunits scom. Checks attribute chip-id of the ocmb target to differentiate between ddr4 and ddr5 ocmb chips for get/put scom
Tested both on odyssey and explorer chips and found it working in both cases properly.
p10bmc:/tmp# getscom odyssey c0002040 -pall
odyssey k0:n0:s0:p02 0x0040010002000640
odyssey k0:n0:s0:p03 0x0040010002000640
odyssey k0:n0:s0:p34 0x0040010002000640
odyssey k0:n0:s0:p35 0x0040010002000640
/usr/bin/edbg getscom odyssey c0002040 -pall
p10bmc:/tmp# ecmdquery chips -dc
cage 0
node 0
slot 0
pu
p[0]
...
...
odyssey
p[2]
mp[0,1]
perv[8]
p[3]
mp[0,1]
perv[8]
p[34]
mp[0,1]
perv[8]
p[35]
mp[0,1]
perv[8]
/usr/bin/edbg ecmdquery chips -dc
=> Ecmd changes to support odyssey chip

src/dll/edbgEcmdDll.C, src/p10/p10_edbgEcmdDllScom.H
If the compatible property and the class name for both proc processor and odyssey processor is same, then we need to check everywhere if that is a chiplet under a proc or under a odyssey. Having a unique name solves the issue.
=> Use a unique class name for ody perv target

src/common/edbgCommon.C, src/common/edbgCommon.H, src/dll/edbgEcmdDll.C, src/p10/p10_edbgEcmdDllScom.C
The explorer chips use fapi position to identify the targets. The odyssey chip uses target index with the recent change. Updating the code to support the same.
=> Use pdbg target index for ody targets
